name: Deploy Azure VM with Script

on:
  push:
    branches:
      - main

jobs:
  deploy-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run VM build script from repo root
        run:  ls -lart
