name: Delete Azure Resource Group

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 18:30 UTC every day or 12:00 IST every day

jobs:
  delete-rg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource group
        run: |
          az group delete --name myrg --yes --no-wait
          az group delete --name NetworkWatcherRG --yes --no-wait
